project:
  type: website 

website:
  title: "QUANT dira-t-on?"
  description: 'Curating notes from a Quant learning journey.'
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/fderyckel/blog
      - icon: twitter
        href: https://twitter.com/Read_the_Dung
format:
  html:
    theme: journal
    css: styles.css

editor: source
