---
title: "04 - Time-series decomposition"
author: "François de Ryckel"
date: "2022-10-21"
categories: [Time-Series]
description: 'Introducing time-series decomposition. We first show how to compose time-series using linear trend, seasonality and then white nosie.'
editor: source
date-modified: "2023-10-22"
---

# Time-series composition 

```{r}
#| message: false
#| warning: false

library(dplyr)
library(ggplot2)
```


## Compose deterministic time-series (with trend and seasonality) with stochastic component 

```{r}
#| label: time_series_composition

df <- tibble(x = 1:252, phi = rnorm(252, mean = 0, sd = 1.5)) |> 
  mutate(y = 0.07 * x + 0.03 + phi)

ggplot(df, aes(x, y)) + 
  geom_line() + 
  ggtitle(label = 'Compose a linear trend with a stochastic component')

  
```

We can also create a seasonality with a stochastic component 

```{r}
df <- tibble(x = 1:252, phi = rnorm(252, mean = 0, sd = 1.5)) |> 
  mutate(y = 1.7 * sin((2 * pi * x / 50) + 0.3 * pi ) + phi)
         
ggplot(df, aes(x, y)) + 
  geom_line() + 
  ggtitle(label = 'Compose a seasonal trend with a stochastic component')
```

## Decomposing a time-series. 



